
resources:
  - name:
    type:
    source:
      branch:
      uri:
      username:
      password:

  - name:
    type:
    source:
      branch:
      uri:
      username:
      password:
 
         